apiVersion: v1
kind: Service
metadata:
  name: mujinjang-api
  namespace: mujinjang
  labels:
    app: mujinjang-api
spec:
  type: NodePort
  selector:
    app: mujinjang-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
