apiVersion: v1
kind: Service
metadata:
  name: mujinjang-mysql
  namespace: mujinjang
  labels:
    app: coupon-mysql
spec:
  ports:
    - port: 3306
      name: mujinjang-mysql
  clusterIP: None
  selector:
    app: mujinjang-mysql
